version: 2

jobs:
  linux:
    docker:
      - image: swift:4.0.3
    steps:
      - run: apt-get install -yq libssl-dev
      - checkout
      - run: swift build
      - run: swift test

workflows:
  version: 2
  tests:
    jobs:
      - linux
